/*
 * Copyright 2026 Adobe Systems Incorporated
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
import { describe, it } from 'node:test';
import assert from 'node:assert/strict';
import { buildPreview } from '../../../../tools/apps/graphql/utils/sdl.js';
import { describeProblem } from '../../../../tools/apps/graphql/utils/messages.js';
import {
  buildSchemaArtifact, createConfig, createDraft, getSaveBlocker, isValidEndpointName,
  parseConfig, serializeConfig, toSavePayload, validateEndpointName,
} from '../../../../tools/apps/graphql/utils/endpoint.js';

const product = {
  type: 'object',
  properties: { title: { type: 'string' } },
};

const loaded = (id, schema = product) => ({
  id, status: 'loaded', schema, valid: true, issues: [],
});

describe('config', () => {
  it('normalises schemas to a unique sorted list', () => {
    assert.deepEqual(createConfig({ name: 'a', schemas: ['b'] }), { name: 'a', schemas: ['b'] });
    assert.deepEqual(createConfig({ name: 'a', schemas: ['b', 'a', 'b', ''] }), { name: 'a', schemas: ['a', 'b'] });
  });

  it('round-trips through serialize and parse, taking the name from the path', () => {
    const text = serializeConfig({ name: 'x', schemas: ['s'] });
    assert.deepEqual(parseConfig({ text, name: 'y' }).config, { name: 'y', schemas: ['s'] });
  });

  it('ignores unknown keys', () => {
    const text = '{"description":"d","name":"x","schemas":["b","a"]}';
    assert.deepEqual(parseConfig({ text, name: 'x' }).config, { name: 'x', schemas: ['a', 'b'] });
  });

  it('reports invalid configurations', () => {
    assert.equal(typeof parseConfig({ text: '{', name: 'a' }).error, 'string');
    assert.equal(typeof parseConfig({ text: '[]', name: 'a' }).error, 'string');
  });

  it('validates endpoint names', () => {
    assert.equal(validateEndpointName({ name: 'marketing-v2' }), undefined);
    assert.equal(typeof validateEndpointName({ name: '' }), 'string');
    assert.equal(typeof validateEndpointName({ name: 'Bad Name' }), 'string');
    assert.equal(typeof validateEndpointName({ name: '1abc' }), 'string');
    assert.equal(typeof validateEndpointName({ name: 'a'.repeat(64) }), 'string');
    assert.ok(validateEndpointName({ name: 'dup', existing: ['dup'] }).includes('already exists'));
    assert.equal(validateEndpointName({ name: 'global' }), undefined);
    assert.equal(validateEndpointName({ name: 'ab' }), 'The endpoint name must be 3–32 characters long.');
    assert.equal(validateEndpointName({ name: 'web' }), undefined);
    assert.equal(validateEndpointName({ name: 'abcd' }), undefined);
    assert.equal(validateEndpointName({ name: 'a'.repeat(32) }), undefined);
    assert.equal(validateEndpointName({ name: 'a'.repeat(33) }), 'The endpoint name must be 3–32 characters long.');
    assert.deepEqual([isValidEndpointName('main'), isValidEndpointName('ab'), isValidEndpointName(3)], [true, false, false]);
  });
});

describe('artifact', () => {
  it('prefixes the SDL with a generated-by header', () => {
    const text = buildSchemaArtifact({ endpoint: 'e', sdl: 'type Query { a: String }', generatedAt: 'now' });
    assert.deepEqual(text.split('\n'), [
      '# @generated by aem-apps graphql - do not edit',
      '# endpoint: e',
      '# generatedAt: now',
      '',
      'type Query { a: String }',
    ]);
  });
});

describe('draft', () => {
  it('starts new endpoints with no schemas', () => {
    assert.deepEqual(createDraft({ name: 'main' }), { name: 'main', schemas: [], isNew: true });
  });

  it('explains why a draft cannot be saved', () => {
    const preview = { sdl: 'x', errors: [] };
    const draft = { ...createDraft(), name: 'main', schemas: ['a'] };
    assert.ok(getSaveBlocker({ draft: { ...draft, name: 'Bad' }, preview }).includes('lowercase'));
    assert.ok(getSaveBlocker({ draft, preview, existing: ['main'] }).includes('already exists'));
    assert.ok(getSaveBlocker({ draft: { ...draft, schemas: [] }, preview }).includes('must be selected'));
    assert.ok(getSaveBlocker({ draft, preview: { sdl: '', errors: ['e'] } }).includes('errors'));
    assert.equal(getSaveBlocker({ draft, preview }), undefined);
  });

  it('produces a save payload whose artifact is current', () => {
    const schemas = [loaded('product')];
    const draft = { ...createDraft(), name: 'main', schemas: ['product'] };
    const preview = buildPreview({ draft, schemas });
    const now = new Date('2024-01-02T03:04:05Z');
    const { config, artifact } = toSavePayload({ draft, preview, now });
    assert.deepEqual(config, { name: 'main', schemas: ['product'] });
    assert.ok(artifact.includes('# generatedAt: 2024-01-02T03:04:05.000Z'));
    assert.equal(artifact.endsWith(`\n\n${preview.sdl}`), true);
  });
});

describe('preview', () => {
  it('builds a preview from usable selected schemas only', () => {
    const draft = { ...createDraft(), schemas: ['broken', 'gone', 'product'] };
    const schemas = [loaded('product'), {
      id: 'broken', status: 'loaded', schema: {}, valid: false,
    }];
    const preview = buildPreview({ draft, schemas });
    assert.deepEqual(preview.errors, []);
    assert.ok(preview.sdl.includes('type Product {'));
    assert.deepEqual(preview.warnings.slice(0, 2).map(describeProblem), [
      'broken: The schema is invalid and was skipped.',
      'gone: The schema no longer exists and was skipped.',
    ]);
  });

  it('builds a preview from the selected usable schemas', () => {
    const schemas = [
      loaded('product'),
      loaded('article'),
      {
        id: 'broken', status: 'loaded', schema: {}, valid: false,
      },
    ];
    const draft = createDraft({ config: { name: 'main', schemas: ['product', 'article', 'broken'] } });
    const preview = buildPreview({ draft, schemas });
    assert.ok(preview.sdl.includes('type Product {'));
    assert.ok(preview.sdl.includes('type Article {'));
    assert.equal(describeProblem(preview.warnings[0]), 'broken: The schema is invalid and was skipped.');
  });

  it('returns an empty preview without selected schemas', () => {
    const draft = { ...createDraft() };
    const preview = buildPreview({ draft, schemas: [loaded('product')] });
    assert.deepEqual(preview, {
      sdl: '', warnings: [], errors: [],
    });
  });

  it('describes converter problems', () => {
    assert.equal(describeProblem({ schemaId: '', pointer: '', message: 'Global.' }), 'Global.');
    assert.equal(describeProblem({ schemaId: 'a', pointer: '/properties/x', message: 'Bad.' }), 'a #/properties/x: Bad.');
  });
});
